name: app_streaming_gastos
description: Aplicación para gestionar gastos de suscripciones de streaming
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Estado y arquitectura
  flutter_riverpod: ^2.5.1
  
  # Base de datos local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Calendario nativo
  device_calendar: ^4.3.3
  
  # Utilidades
  intl: ^0.19.0
  uuid: ^4.3.3
  timezone: ^0.9.2
  
  # Iconos
  cupertino_icons: ^1.0.6
  flutter_iconpicker: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
